// List of audio files and labels
const audioList = [
    { file: '了.m4a', label: 'le' },
    { file: '我.m4a', label: 'le' },
    { file: '我们.m4a', label: 'le' },
    { file: '你.m4a', label: 'le' },
    { file: '你们.m4a', label: 'le' },
    { file: '他她.m4a', label: 'le' },
    { file: '这.m4a', label: 'le' },
    { file: '哪.m4a', label: 'le' },
    { file: '那.m4a', label: 'le' },
    { file: '谁.m4a', label: 'le' },
    { file: '什么.m4a', label: 'le' },
    { file: '多少.m4a', label: 'le' },
    { file: '几.m4a', label: 'le' },
    { file: '怎么.m4a', label: 'le' },
    { file: '怎么样.m4a', label: 'le' },
    { file: '一.m4a', label: 'le' },
    { file: '二.m4a', label: 'le' },
    { file: '三.m4a', label: 'le' },
    { file: '四.m4a', label: 'le' },
    { file: '五.m4a', label: 'le' },
    { file: '六.m4a', label: 'le' },
    { file: '七.m4a', label: 'le' },
    { file: '八.m4a', label: 'le' },
    { file: '九.m4a', label: 'le' },
    { file: '十.m4a', label: 'le' },
    { file: '零.m4a', label: 'le' },
    { file: '个.m4a', label: 'le' },
    { file: '岁.m4a', label: 'le' },
    { file: '本.m4a', label: 'le' },
    { file: '些.m4a', label: 'le' },
    { file: '快.m4a', label: 'le' },
    { file: '不.m4a', label: 'le' },
    { file: '没.m4a', label: 'le' },
    { file: '很.m4a', label: 'le' },
    { file: '太.m4a', label: 'le' },
    { file: '都.m4a', label: 'le' },
    { file: '和.m4a', label: 'le' },
    { file: '在.m4a', label: 'le' },
    { file: '的.m4a', label: 'le' },
    { file: '吗.m4a', label: 'le' },
    { file: '呢.m4a', label: 'le' },
    { file: '喂.m4a', label: 'le' },
    { file: '家.m4a', label: 'le' },
    { file: '学校.m4a', label: 'le' },
    { file: '饭店.m4a', label: 'le' },
    { file: '商店.m4a', label: 'le' },
    { file: '医院.m4a', label: 'le' },
    { file: '火车站.m4a', label: 'le' },
    { file: '中国.m4a', label: 'le' },
    { file: '北京.m4a', label: 'le' },
    { file: '上.m4a', label: 'le' },
    { file: '下.m4a', label: 'le' },
    { file: '前面.m4a', label: 'le' },
    { file: '后面.m4a', label: 'le' },
    { file: '里面.m4a', label: 'le' },
    { file: '今天.m4a', label: 'le' },
    { file: '明天.m4a', label: 'le' },
    { file: '昨天.m4a', label: 'le' },
    { file: '上午.m4a', label: 'le' },
    { file: '中午.m4a', label: 'le' },
    { file: '下午.m4a', label: 'le' },
    { file: '年.m4a', label: 'le' },
    { file: '月.m4a', label: 'le' },
    { file: '日.m4a', label: 'le' },
    { file: '星期.m4a', label: 'le' },
    { file: '点.m4a', label: 'le' },
    { file: '分钟.m4a', label: 'le' },
    { file: '现在.m4a', label: 'le' },
    { file: '时候.m4a', label: 'le' },
    { file: '爸爸.m4a', label: 'le' },
    { file: '妈妈.m4a', label: 'le' },
    { file: '儿子.m4a', label: 'le' },
    { file: '女儿.m4a', label: 'le' },
    { file: '老师.m4a', label: 'le' },
    { file: '学生.m4a', label: 'le' },
    { file: '同学.m4a', label: 'le' },
    { file: '朋友.m4a', label: 'le' },
    { file: '医生.m4a', label: 'le' },
    { file: '先生.m4a', label: 'le' },
    { file: '小姐.m4a', label: 'le' },
    { file: '衣服.m4a', label: 'le' },
    { file: '水.m4a', label: 'le' },
    { file: '菜.m4a', label: 'le' },
    { file: '米饭.m4a', label: 'le' },
    { file: '水果.m4a', label: 'le' },
    { file: '苹果.m4a', label: 'le' },
    { file: '茶.m4a', label: 'le' },
    { file: '杯子.m4a', label: 'le' },
    { file: '钱.m4a', label: 'le' },
    { file: '飞机.m4a', label: 'le' },
    { file: '出租车.m4a', label: 'le' },
    { file: '电视.m4a', label: 'le' },
    { file: '电脑.m4a', label: 'le' },
    { file: '电影.m4a', label: 'le' },
    { file: '天气.m4a', label: 'le' },
    { file: '猫.m4a', label: 'le' },
    { file: '狗.m4a', label: 'le' },
    { file: '东西.m4a', label: 'le' },
    { file: '人.m4a', label: 'le' },
    { file: '名字.m4a', label: 'le' },
    { file: '书.m4a', label: 'le' },
    { file: '汉语.m4a', label: 'le' },
    { file: '子.m4a', label: 'le' },
    { file: '桌子.m4a', label: 'le' },
    { file: '椅子.m4a', label: 'le' },
    { file: '谢谢.m4a', label: 'le' },
    { file: '不客气.m4a', label: 'le' },
    { file: '再见.m4a', label: 'le' },
    { file: '请.m4a', label: 'le' },
    { file: '对不起.m4a', label: 'le' },
    { file: '没关系.m4a', label: 'le' },
    { file: '是.m4a', label: 'le' },
    { file: '有.m4a', label: 'le' },
    { file: '看.m4a', label: 'le' },
    { file: '听.m4a', label: 'le' },
    { file: '说话.m4a', label: 'le' },
    { file: '读.m4a', label: 'le' },
    { file: '写.m4a', label: 'le' },
    { file: '看见.m4a', label: 'le' },
    { file: '叫.m4a', label: 'le' },
    { file: '来.m4a', label: 'le' },
    { file: '回.m4a', label: 'le' },
    { file: '去.m4a', label: 'le' },
    { file: '吃.m4a', label: 'le' },
    { file: '喝.m4a', label: 'le' },
    { file: '睡觉.m4a', label: 'le' },
    { file: '打电话.m4a', label: 'le' },
    { file: '做.m4a', label: 'le' },
    { file: '买.m4a', label: 'le' },
    { file: '开.m4a', label: 'le' },
    { file: '坐.m4a', label: 'le' },
    { file: '住.m4a', label: 'le' },
    { file: '学习.m4a', label: 'le' },
    { file: '工作.m4a', label: 'le' },
    { file: '下雨.m4a', label: 'le' },
    { file: '爱.m4a', label: 'le' },
    { file: '喜欢.m4a', label: 'le' },
    { file: '想.m4a', label: 'le' },
    { file: '认识.m4a', label: 'le' },
    { file: '会.m4a', label: 'le' },
    { file: '能.m4a', label: 'le' },
    { file: '好.m4a', label: 'le' },
    { file: '大.m4a', label: 'le' },
    { file: '小.m4a', label: 'le' },
    { file: '多.m4a', label: 'le' },
    { file: '少.m4a', label: 'le' },
    { file: '冷.m4a', label: 'le' },
    { file: '热.m4a', label: 'le' },
    { file: '高兴.m4a', label: 'le' },
    { file: '漂亮.m4a', label: 'le' }, 
  ];
  
  // Array to keep track of remaining audio files
  let remaining = [...audioList];
  
  // Select the generate button
  const generateButton = document.querySelector('.generate-button');
  
  // Event listener for the button
  generateButton.addEventListener('click', () => {
    if (remaining.length === 0) {
      // Reset the array once all files have been played
      remaining = [...audioList];
    }
  
    // Randomly select an audio file from the remaining list
    const index = Math.floor(Math.random() * remaining.length);
    const current = remaining[index];
  
    // Remove the selected file from the remaining list
    remaining.splice(index, 1);
  
    // Play the selected audio file
    const audio = new Audio(`audio/${current.file}`);
    audio.play().catch((error) => {
      console.error('Audio failed to play:', error);
    });
  }); 
  

  
  